server:
    port: 8081
    servlet:
        context-path: /flowersys
spring:
    servlet:
        multipart:
            max-file-size: 10MB
    datasource:
        name: SpringBootQuartz
        url: jdbc:mysql://127.0.0.1:3306/flowerdb?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: mysql
        # 使用Druid数据源
        type: com.zaxxer.hikari.util.DriverDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
 #       druid:
 #           filters: stat
 #           maxActive: 20
 #           initialSize: 1
 #           maxWait: 60000
 #           minIdle: 1
 #           timeBetweenEvictionRunsMillis: 60000
 #           minEvictableIdleTimeMillis: 300000
 #           validationQuery: select 'x'
 #           testWhileIdle: true
 #           testOnBorrow: false
 #           testOnReturn: false
 #           poolPreparedStatements: true
 #           maxOpenPreparedStatements: 20
    # 开启thymeleaf必须关闭404交给异常处理器处理配置
    # 不然无法访问静态资源
    thymeleaf:
        # 开发时关闭缓存不然没法看到实时页面
        cache: false
        # 启用不严格检查
        mode: LEGACYHTML5

mybatis:
    # Mybatis配置Mapper路径
    mapper-locations: classpath:dao/*.xml

pagehelper:
    params: count=countSql
    # 指定分页插件使用哪种方言
    helper-dialect: mysql
    # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
    reasonable: 'true'
    support-methods-arguments: 'true'

mapper:
    # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
    not-empty: true

logging:
    # Debug打印SQL
    level.com.junhow.gp.dao: debug

#操作系统的资源文件路径，作为映射路径的真实路径
resourcelocation: E:/upload/
ip: 127.0.0.1:8081
